// Packaging icon-validity test — the PKG-04 icon-source proof.
//
// Proves the committed `build/icon.png` is a structurally valid PNG whose dimensions clear
// the >=256x256 source floor electron-builder enforces when it generates the Windows .ico
// (app-builder-lib/util/iconConverter.js `recommendedMin` = 256). electron-builder 26.x's
// icon tool rejects a .ico as INPUT ("Unsupported input format .ico. Supported: .png, .svg,
// .icns"), so the committed source is a PNG and the Windows .ico is generated from it at
// package time.
//
// The check parses the on-disk bytes with checked reads only (readUInt8 / readUInt32BE,
// never raw `buf[i]` indexing — the repo runs `noUncheckedIndexedAccess`, D-08):
//   • 8-byte PNG signature (89 50 4E 47 0D 0A 1A 0A).
//   • first chunk is IHDR: 4-byte length == 13, type "IHDR", then width/height (big-endian
//     uint32), bit depth, and color type (6 = RGBA).
// Asserts width and height are both >=256. This gates any future icon swap (D-03) — a
// replacement source below the floor fails here before it can fail a build.
//
// Covers PKG-04. Harness: node:test via tsx (matches the repo — NOT Vitest).

import { describe, test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

// The committed placeholder icon source (generated by scripts/make-icon.mjs, D-03). Read-only.
const ICON: Buffer = readFileSync('build/icon.png');

const PNG_SIGNATURE = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a];

describe('build/icon.png clears electron-builder 256x256 source floor (PKG-04)', () => {
  test('has a valid 8-byte PNG signature', () => {
    assert.ok(ICON.length >= 8, 'file must be at least an 8-byte PNG signature');
    for (let i = 0; i < PNG_SIGNATURE.length; i++) {
      assert.equal(
        ICON.readUInt8(i),
        PNG_SIGNATURE[i],
        `PNG signature byte ${i} must match`,
      );
    }
  });

  test('first chunk is IHDR declaring an RGBA image >= 256x256', () => {
    // After the 8-byte signature: 4-byte chunk length, 4-byte chunk type ("IHDR"), then data.
    assert.ok(ICON.length >= 8 + 8 + 13, 'file must be large enough to hold an IHDR chunk');
    const chunkLength = ICON.readUInt32BE(8);
    assert.equal(chunkLength, 13, 'IHDR chunk data length must be 13 bytes');
    const type = ICON.toString('ascii', 12, 16);
    assert.equal(type, 'IHDR', 'first chunk must be IHDR');

    // IHDR data starts at offset 16: width(4) height(4) bitDepth(1) colorType(1) ...
    const width = ICON.readUInt32BE(16);
    const height = ICON.readUInt32BE(20);
    const bitDepth = ICON.readUInt8(24);
    const colorType = ICON.readUInt8(25);

    assert.equal(bitDepth, 8, 'bit depth must be 8');
    assert.equal(colorType, 6, 'color type must be 6 (RGBA)');
    assert.ok(
      width >= 256 && height >= 256,
      `build/icon.png must be >=256x256 (found ${width}x${height}) — electron-builder source floor, iconConverter recommendedMin`,
    );
  });
});
