// Packaging icon-validity test — the PKG-04 icon-floor proof.
//
// Proves the committed `build/icon.ico` is a structurally valid Windows ICO whose
// largest entry is >=256x256 — the hard floor electron-builder's Windows target
// enforces (06-RESEARCH Pitfall 3: a sub-256 icon fails the build immediately).
//
// The check parses the on-disk bytes with checked reads only (readUInt8 / readUInt16LE,
// never raw `buf[i]` indexing — the repo runs `noUncheckedIndexedAccess`, D-08):
//   • 6-byte ICONDIR header: reserved (offset 0) == 0, type (offset 2) == 1 (icon),
//     count (offset 4) >= 1.
//   • each 16-byte ICONDIRENTRY (starting at offset 6): width byte + height byte, with
//     the ICO convention that a stored `0` means 256px.
// Asserts at least one entry is >=256 in BOTH dimensions. This gates any future icon
// swap (D-03) — a replacement icon below the floor fails here before it can fail a build.
//
// Covers PKG-04. Harness: node:test via tsx (matches the repo — NOT Vitest).

import { describe, test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

// The committed placeholder icon (generated by scripts/make-icon.mjs, D-03). Read-only.
const ICON: Buffer = readFileSync('build/icon.ico');

describe('build/icon.ico clears electron-builder 256x256 floor (PKG-04)', () => {
  test('has a valid ICONDIR header (reserved 0, type icon, count >= 1)', () => {
    // 6-byte ICONDIR: reserved(2) + type(2) + count(2), all little-endian.
    assert.ok(ICON.length >= 6, 'icon must be at least a 6-byte ICONDIR header');
    const reserved = ICON.readUInt16LE(0);
    const type = ICON.readUInt16LE(2);
    const count = ICON.readUInt16LE(4);
    assert.equal(reserved, 0, 'ICONDIR reserved field must be 0');
    assert.equal(type, 1, 'ICONDIR type must be 1 (icon, not cursor)');
    assert.ok(count >= 1, 'ICONDIR count must declare at least one entry');
  });

  test('at least one ICONDIRENTRY is >= 256x256 (0-byte dimension means 256)', () => {
    const count = ICON.readUInt16LE(4);
    // Each ICONDIRENTRY is 16 bytes, starting immediately after the 6-byte ICONDIR.
    assert.ok(
      ICON.length >= 6 + count * 16,
      'buffer must be large enough to hold every declared ICONDIRENTRY',
    );

    let largest = 0;
    let hasFloorEntry = false;
    for (let n = 0; n < count; n++) {
      const base = 6 + n * 16;
      // ICO convention: a stored dimension byte of 0 encodes 256 (the max in one byte).
      const rawWidth = ICON.readUInt8(base);
      const rawHeight = ICON.readUInt8(base + 1);
      const width = rawWidth === 0 ? 256 : rawWidth;
      const height = rawHeight === 0 ? 256 : rawHeight;
      largest = Math.max(largest, Math.min(width, height));
      if (width >= 256 && height >= 256) {
        hasFloorEntry = true;
      }
    }

    assert.ok(
      hasFloorEntry,
      `build/icon.ico must contain a >=256x256 entry (largest square dimension found: ${largest}) — electron-builder Windows floor, RESEARCH Pitfall 3`,
    );
  });
});
